#!/usr/bin/env python3
"""
Does keyword matching actually fail on this task, or did it only fail on
truncated text?

Phase 2 concluded that a keyword rule was inadequate for CNS trials and that a
fine-tuned transformer was needed. That conclusion was reached with the stored
`Outcome text (for cognition check)` column, which is truncated at a median of
400 characters against ~1,760 in the ClinicalTrials.gov outcome module.

The decisive test is the subset of trials the human labelled Yes that the
original keyword flagging did NOT flag. Those are the trials the labeller had to
catch by reading the registry page, and they are the reason the task looked hard.
If the same keyword list recovers them once it is given complete text, then the
apparent inadequacy was a text problem, not a language problem.

    python analysis/fetch_full_outcome_text.py     # first
    python analysis/truncation_recall_test.py

Writes results/truncation_recall_test.json and .md.
"""

import csv
import json
import statistics
from collections import Counter

SRC = "data/CLASSIFIER_training_population.csv"
FULL = "data/derived/ctgov_full_outcome_text.csv"
KEYWORDS = "data/derived/cognitive_keywords.json"


def load():
    full = {r["trial_id"]: r["full_outcome_text"]
            for r in csv.DictReader(open(FULL, newline="", encoding="utf-8"))}
    keywords = json.load(open(KEYWORDS))["keywords"]
    seen, rows = set(), []
    for r in csv.DictReader(open(SRC, newline="", encoding="utf-8", errors="replace")):
        tid = (r.get("NCT/TrialID") or "").strip()
        if tid in seen or tid not in full:
            continue
        seen.add(tid)
        rows.append({
            "trial_id": tid,
            "cancer_type": (r.get("Cancer Type") or "").strip(),
            "pool": (r.get("Pool") or "").strip(),
            "flagged": bool((r.get("Flagged Keyword(s)") or "").strip()),
            "label": (r.get("Measures cognition? (Y/N)") or "").strip() == "Yes",
            "stored_text": (r.get("Outcome text (for cognition check)") or "").strip(),
            "full_text": full[tid],
        })
    return rows, keywords


def matches(text, keywords):
    low = text.lower()
    return any(k in low for k in keywords)


def main():
    rows, keywords = load()

    # The subset that made the task look hard: human said Yes, the original
    # keyword flagging did not flag it.
    hard = [r for r in rows if r["label"] and not r["flagged"]]
    hard_stored = sum(1 for r in hard if matches(r["stored_text"], keywords))
    hard_full = sum(1 for r in hard if matches(r["full_text"], keywords))

    positives = [r for r in rows if r["label"]]
    recall_stored = sum(1 for r in positives if matches(r["stored_text"], keywords))
    recall_full = sum(1 for r in positives if matches(r["full_text"], keywords))

    negatives = [r for r in rows if not r["label"]]
    fp_full = [r for r in negatives if matches(r["full_text"], keywords)]

    result = {
        "n_trials": len(rows),
        "n_positive": len(positives),
        "n_negative": len(negatives),
        "pool_composition": dict(Counter(f"{r['pool']}/{'Yes' if r['label'] else 'No'}"
                                         for r in rows)),
        "median_chars": {
            "stored_column": statistics.median(len(r["stored_text"]) for r in rows),
            "ctgov_outcome_module": statistics.median(len(r["full_text"]) for r in rows),
        },
        "recall_all_positives": {
            "on_stored_text": f"{recall_stored}/{len(positives)}",
            "on_full_text": f"{recall_full}/{len(positives)}",
        },
        "decisive_subset_labelled_yes_but_never_flagged": {
            "n": len(hard),
            "recovered_on_stored_text": hard_stored,
            "recovered_on_full_text": hard_full,
        },
        "false_positives_on_full_text": {
            "n": len(fp_full),
            "by_cancer_type": dict(Counter(r["cancer_type"] for r in fp_full)),
            "trial_ids": [r["trial_id"] for r in fp_full],
        },
        "specificity_caveat": (
            "The negative pool was selected to be negative, so specificity "
            "estimated on this dataset is not unbiased and no specificity figure "
            "is reported here. Recall is interpretable because the decisive "
            "subset was labelled Yes by human reading, independently of the "
            "keyword flag that failed to surface it."
        ),
    }

    with open("results/truncation_recall_test.json", "w") as f:
        json.dump(result, f, indent=2)

    with open("results/truncation_recall_test.md", "w") as f:
        f.write(f"""# Was keyword matching ever the problem?

Generated by `analysis/truncation_recall_test.py` over {len(rows)} training
trials with a retrievable ClinicalTrials.gov outcome module.

## Text available to the classifier

| Source | Median characters |
|---|---|
| `Outcome text (for cognition check)` (as used in Phase 2) | {result['median_chars']['stored_column']:.0f} |
| ClinicalTrials.gov outcome module | {result['median_chars']['ctgov_outcome_module']:.0f} |

## The decisive subset

{len(hard)} trials were labelled **Yes** by human review while carrying **no
keyword flag**. These are the trials the labeller had to catch by reading, and
they are the reason the task appeared to need a language model.

| Keyword rule applied to | Recovered |
|---|---|
| The stored, truncated text | **{hard_stored} / {len(hard)}** |
| The full registry outcome text | **{hard_full} / {len(hard)}** |

Recall across all {len(positives)} positives rises from
{recall_stored}/{len(positives)} on stored text to {recall_full}/{len(positives)}
on full text.

## False positives on full text

{len(fp_full)} trials matched a cognitive term while the human judged no
registered neurocognitive outcome: {', '.join(r['trial_id'] for r in fp_full)}
(all {', '.join(sorted(set(r['cancer_type'] for r in fp_full)))}).

## What this does and does not establish

It establishes that the recall failure attributed to keyword matching in Phase 2
was a property of the truncated input, not of the method. The same 66-term list,
unchanged, recovers every positive once the text is complete.

It does **not** establish specificity. The negative pool in this dataset was
selected to be negative, so a specificity estimate computed here would be
optimistic by construction, and none is reported. Establishing specificity
requires a random sample of registry records, not this enriched design.
""")

    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
